### ISSUE TITLE
Not able to run this repo.

### ISSUE THREAD

**Issue by yashsaxena** [gburtini/Potent-Tools-for-XPath#7]
It seems the repo has some error. Not able to run this. 

As listed on npm, runkit ( https://npm.runkit.com/potent) throws error - Error: Cannot find module 'js-xpath'
Again in package.json & yarn file - the links to js-xpath refer to the github page of js-xpath which is odd.

**Comment by gburtini** [comment]
I realize this issue is 3 years old but when the package was initially published `js-xpath` was not published to NPM. The preferred format of package.json git dependencies has changed over time. 

Anyway, https://github.com/gburtini/Potent-Tools-for-XPath/commit/7013d38123c2d605571fee996877c634a9717576 plus a rebuild of the `yarn.lock` file should resolve this for you.
